version: '3.9'

services:
  web:
    image: mcr.microsoft.com/dotnet/aspnet:6.0
    container_name: myapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - JAEGER_AGENT_HOST=jaeger
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
      - kibana
      - jaeger
    volumes:
      - ./myapp:/app
    command: "dotnet myapp.dll"
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  
  jaeger:
    image: jaegertracing/all-in-one:1.27
    container_name: jaeger
    ports:
      - "16686:16686"
      - "6831:6831/udp"
      - "6832:6832/udp"
